name: Trigger Action
description: This action triggered by a specific event.
inputs:
  workflow-ref:
    description: The reference of the workflow to trigger (tag or branch).
    requred: true
  workflow-path:
    description: The path to the execute workflow file.
    requred: true
  build-version:
    description: The version to be used.
    requred: false
    default: ''

runs:
  using: composite
  steps:
    - name: Validate workflow file exists
      shell: bash
      run: |
        WORKFLOW_PATH="${{ inputs.workflow-path }}"
        if [ ! -f "$WORKFLOW_PATH" ]; then
          echo "❌ Error: Workflow file does not exist: $WORKFLOW_PATH"
          exit 1
        fi
        echo "✅ Workflow file exists: $WORKFLOW_PATH"

    - name: Trigger the workflow
      id: trigger_workflow
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run ${{ inputs.workflow-path }} --ref ${{ inputs.workflow-ref }} --field build_version=${{ inputs.build-version }}
