name: Trigger Action
description: This action triggered by a specific event.
inputs:
  workflow-ref:
    description: The reference of the workflow to trigger (tag or branch).
    required: false
    default: ${{ github.ref_name }}
  workflow-path:
    description: The path to the execute workflow file.
    required: true
  build-version:
    description: The version to be used.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Validate workflow file exists
      shell: bash
      run: |
        WORKFLOW_PATH="${{ inputs.workflow-path }}"
        if [ ! -f "$WORKFLOW_PATH" ]; then
          echo "❌ Error: Workflow file does not exist: $WORKFLOW_PATH"
          exit 1
        fi
        echo "✅ Workflow file exists: $WORKFLOW_PATH"

    - name: Check for running workflows
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        WORKFLOW_FILE=$(basename ${{ inputs.workflow-path }})
        TARGET_REF="${{ inputs.workflow-ref }}"
        
        echo "Checking for running workflows..."
        echo "Workflow: $WORKFLOW_FILE"
        echo "Reference: $TARGET_REF"
        
        # Get running or queued workflows for this workflow file and reference
        RUNNING_WORKFLOWS=$(gh run list \
          --workflow="$WORKFLOW_FILE" \
          --branch="$TARGET_REF" \
          --status="in_progress" \
          --json databaseId,status,displayTitle,createdAt \
          --limit 10)
        
        QUEUED_WORKFLOWS=$(gh run list \
          --workflow="$WORKFLOW_FILE" \
          --branch="$TARGET_REF" \
          --status="queued" \
          --json databaseId,status,displayTitle,createdAt \
          --limit 10)
        
        # Count running workflows
        RUNNING_COUNT=$(echo "$RUNNING_WORKFLOWS" | jq 'length')
        QUEUED_COUNT=$(echo "$QUEUED_WORKFLOWS" | jq 'length')
        TOTAL_COUNT=$((RUNNING_COUNT + QUEUED_COUNT))
        
        if [ "$TOTAL_COUNT" -gt 0 ]; then
          echo "::error::Found $TOTAL_COUNT active workflow(s) for $WORKFLOW_FILE on branch $TARGET_REF"
          echo ""
          echo "Running workflows ($RUNNING_COUNT):"
          echo "$RUNNING_WORKFLOWS" | jq -r '.[] | "  - Run ID: \(.databaseId), Title: \(.displayTitle), Created: \(.createdAt)"'
          echo ""
          echo "Queued workflows ($QUEUED_COUNT):"
          echo "$QUEUED_WORKFLOWS" | jq -r '.[] | "  - Run ID: \(.databaseId), Title: \(.displayTitle), Created: \(.createdAt)"'
          echo ""
          echo "::error::Cannot trigger workflow while another instance is running. Please wait for the current workflow to complete or cancel it manually."
          exit 1
        fi
        
        echo "✅ No active workflows found. Safe to trigger."

    - name: Trigger the workflow
      id: trigger_workflow
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run ${{ inputs.workflow-path }} --ref ${{ inputs.workflow-ref }} --field build-version=${{ inputs.build-version }}

        # Wait a moment for the workflow to be created
        sleep 3
        
        # Get the most recent workflow run
        WORKFLOW_FILE=$(basename ${{ inputs.workflow-path }})
        RUN_DATA=$(gh run list --workflow="$WORKFLOW_FILE" --limit 1 --json databaseId,url,status,createdAt,displayTitle)
        
        if [ -n "$RUN_DATA" ]; then
          RUN_URL=$(echo "$RUN_DATA" | jq -r '.[0].url')
          RUN_ID=$(echo "$RUN_DATA" | jq -r '.[0].databaseId')
          RUN_STATUS=$(echo "$RUN_DATA" | jq -r '.[0].status')
          RUN_TITLE=$(echo "$RUN_DATA" | jq -r '.[0].displayTitle')
          
          echo "✅ Workflow triggered successfully"
          echo "Run ID: $RUN_ID"
          echo "Run URL: $RUN_URL"
          
          # Set output
          echo "workflow-run-url=$RUN_URL" >> "$GITHUB_OUTPUT"
          
          # Create job summary
          {
            echo "## Deployment Workflow Triggered"
            echo ""
            echo "| Property | Value |"
            echo "|----------|-------|"
            echo "| **Workflow** | \`$WORKFLOW_FILE\` |"
            echo "| **Reference** | \`${{ inputs.workflow-ref }}\` |"
            echo "| **Run ID** | [\`$RUN_ID\`]($RUN_URL) |"
            echo "| **Status** | \`$RUN_STATUS\` |"
            echo "| **Title** | $RUN_TITLE |"
            echo ""
            echo "### Quick Links"
            echo "- [View Workflow Run]($RUN_URL)"
            echo "- [View All Runs](https://github.com/${{ github.repository }}/actions/workflows/$WORKFLOW_FILE)"
          } >> "$GITHUB_STEP_SUMMARY"
        else
          echo "Workflow triggered but run details could not be retrieved"
          
          # Set empty output
          echo "workflow-run-url=" >> "$GITHUB_OUTPUT"
          
          {
            echo "## Deployment Workflow Triggered"
            echo ""
            echo "| Property | Value |"
            echo "|----------|-------|"
            echo "| **Workflow** | \`$WORKFLOW_FILE\` |"
            echo "| **Reference** | \`${{ inputs.workflow-ref }}\` |"
            echo ""
            echo "Workflow triggered successfully, but run details could not be retrieved immediately."
          } >> "$GITHUB_STEP_SUMMARY"
        fi
