name: Trigger Action
description: This action triggered by a specific event.
inputs:
  workflow-ref:
    description: The reference of the workflow to trigger (tag or branch).
    required: false
    default: ${{ github.ref_name }}
  workflow-path:
    description: The path to the execute workflow file.
    required: true
  build-version:
    description: The version to be used.
    required: false
    default: ''

outputs:
  workflow-run-url:
    description: The URL of the triggered workflowrun.
    value: ${{ steps.trigger-workflow.outputs.workflow-run-url }}
  workflow-run-id:
    description: The ID of the triggered workflow run.
    value: ${{ steps.trigger-workflow.outputs.workflow-run-id }}

runs:
  using: composite
  steps:
    - name: Validate workflow file exists
      shell: bash
      run: |
        WORKFLOW_PATH="${{ inputs.workflow-path }}"
        if [ ! -f "$WORKFLOW_PATH" ]; then
          echo "::error::Workflow file does not exist: $WORKFLOW_PATH"
          exit 1
        fi
        echo "✅ Workflow file exists: $WORKFLOW_PATH"
    
    - name: Trigger workflow
      id: trigger-workflow
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          const path = require('path');
          const fs = require('fs');
          
          const workflowPath = '${{ inputs.workflow-path }}';
          const workflowRef = '${{ inputs.workflow-ref }}';
          const workflowFile = path.basename(workflowPath);
          
          console.log('🚀 Triggering workflow...');
          console.log(`Workflow: ${workflowFile}`);
          console.log(`Reference: ${workflowRef}`);
          
          // Trigger the workflow
          try {
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflowFile,
              ref: workflowRef
            });
            
            console.log('✅ Workflow dispatch request sent successfully');
          } catch (error) {
            core.setFailed(`Failed to trigger workflow: ${error.message}`);
            return;
          }
          
          // Wait for workflow to be created
          await new Promise(resolve => setTimeout(resolve, 3000));
          
          // Find the most recent workflow run
          async function findWorkflowRun(retries = 0) {
            const maxRetries = 5;
            const retryDelay = 2000;
            
            try {
              console.log(`Searching for workflow run (attempt ${retries + 1}/${maxRetries + 1})...`);
              
              const runsResponse = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowFile,
                per_page: 5
              });
              
              if (runsResponse.data.workflow_runs.length > 0) {
                const run = runsResponse.data.workflow_runs[0];
                return {
                  found: true,
                  id: run.id,
                  url: run.html_url,
                  status: run.status,
                  displayTitle: run.display_title
                };
              }
              
              if (retries < maxRetries) {
                console.log(`Run not found yet, retrying in ${retryDelay/1000} seconds...`);
                await new Promise(resolve => setTimeout(resolve, retryDelay));
                return await findWorkflowRun(retries + 1);
              }
              
              return { found: false };
              
            } catch (error) {
              console.error(`Error searching for workflow run: ${error.message}`);
              if (retries < maxRetries) {
                await new Promise(resolve => setTimeout(resolve, retryDelay));
                return await findWorkflowRun(retries + 1);
              }
              return { found: false };
            }
          }
          
          const result = await findWorkflowRun();
          
          if (result.found) {
            console.log('✅ Workflow triggered successfully');
            console.log(`Run ID: ${result.id}`);
            console.log(`Run URL: ${result.url}`);
            
            // Set outputs
            core.setOutput('workflow-run-url', result.url);
            core.setOutput('workflow-run-id', result.id);
            
            // Create job summary
            await core.summary
              .addHeading(`Workflow ${workflowFile} Triggered`, 2)
              .addTable([
                [
                  { data: 'Property', header: true },
                  { data: 'Value', header: true }
                ],
                ['**Workflow**', `\`${workflowFile}\``],
                ['**Reference**', `\`${workflowRef}\``],
                ['**Run ID**', `\`${result.id}\``],
                ['**Run URL**', `[Workflow run](${result.url})`],
                ['**Status**', `\`${result.status}\``]
              ])
              .addHeading('Quick Links', 3)
              .addList([
                `[View Workflow Run](${result.url})`,
                `[View All Runs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/workflows/${workflowFile})`
              ])
              .write();
          } else {
            console.log('⚠️ Workflow triggered but run details could not be retrieved');
            
            // Set empty outputs
            core.setOutput('workflow-run-url', '');
            core.setOutput('workflow-run-id', '');
            
            // Create job summary
            await core.summary
              .addHeading('Deployment Workflow Triggered', 2)
              .addTable([
                [
                  { data: 'Property', header: true },
                  { data: 'Value', header: true }
                ],
                ['**Workflow**', `\`${workflowFile}\``],
                ['**Reference**', `\`${workflowRef}\``]
              ])
              .addRaw('\n\nWorkflow triggered successfully, but run details could not be retrieved immediately.')
              .write();
          }
